name: sphia
description: Sphia - a Proxy Handling Intuitive Application
publish_to: 'none'

version: 0.8.0+11

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.1.2
  dart_ping: ^9.0.1
  drift: ^2.11.0
  dropdown_search: ^5.0.6
  file_picker: ^6.1.1
  fixnum: ^1.1.0
  fl_chart: ^0.67.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  grpc: ^3.2.2
  http: ^1.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  launch_at_startup: ^0.2.2
  logger: ^2.1.0
  path: ^1.8.3
  path_provider: ^2.0.15
  protobuf: ^3.0.0
  pub_semver: ^2.1.4
  qr_flutter: ^4.1.0
  quiver: ^3.2.1
  riverpod_annotation: ^2.3.5
  sqlite3_flutter_libs: ^0.5.0
  tray_manager: ^0.2.1
  tuple: ^2.0.2
  updat: ^1.3.1
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.4
  drift_dev: ^2.11.0
  freezed: ^2.4.7
  json_serializable: ^6.7.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/sphia.db
    - assets/tray_color_off.ico
    - assets/tray_color_on.ico
    - assets/tray_no_color_off.png
    - assets/tray_no_color_on.png
    - assets/logo_about.png
    - assets/app_icon.ico
    - assets/app_icon.png

flutter_intl:
  enabled: true
  main_locale: en_US
  output_dir: lib/l10n/generated